import Head from 'next/head'
import React from 'react'
import { container } from '../interface/types'

const PageLayoud: React.FC<container> = ({ children, title }) => {
    return (
        <Head>
            <title>Next 12 test</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default PageLayoud