import Head from 'next/head'
import React from 'react'
import styles from './PageLayoud.module.css'
import { container } from '../interface/types'
import { LazyMotion, domAnimation } from 'framer-motion'
const PageLayoud: React.FC<container> = ({ children, title, styleContainer }) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.container} ${styles[styleContainer]}`}>
                <LazyMotion features={domAnimation}>
                    {children}
                </LazyMotion>
            </main>
        </>
    )
}

export default PageLayoud